//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tur.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TourBaseEntities1 : DbContext
    {
        public TourBaseEntities1()
            : base("name=TourBaseEntities1")
        {
        }
    
        private static TourBaseEntities1 _context;
        public static TourBaseEntities1 GetContext()
        {
            if (_context == null)
                    _context = new TourBaseEntities1();
                return _context;
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<goroda> goroda { get; set; }
        public virtual DbSet<otvetstv> otvetstv { get; set; }
        public virtual DbSet<otziv> otziv { get; set; }
        public virtual DbSet<programma> programma { get; set; }
        public virtual DbSet<status> status { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<tour> tour { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
