//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tur.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class tour
    {
        public int id { get; set; }
        public int napravlenie_id { get; set; }
        public int status_id { get; set; }
        public string hotel { get; set; }
        public int proggrama_id { get; set; }
        public System.DateTime sroki_pri { get; set; }
        public System.DateTime sroki_ot { get; set; }
        public int otvetstv_id { get; set; }
    
        public virtual goroda goroda { get; set; }
        public virtual otvetstv otvetstv { get; set; }
        public virtual programma programma { get; set; }
        public virtual status status { get; set; }
    }
}
